"""
Real company profiles for live testing - well-known companies
"""
REAL_COMPANY_PROFILES = [
    {
        "id": "real1",
        "name": "Stripe",
        "company": "Stripe",
        "headline": "Financial infrastructure for the internet",
        "industry": "Fintech",
        "sub_industry": "Payments",
        "location": "San Francisco, CA",
        "founded": 2010,
        "valuation": 91500000000,
        "arr": 25000000000,
        "employees": 8000,
        "stage": "Late Stage",
        "status": "Private",
        "description": "Stripe builds economic infrastructure for the internet. Millions of businesses of every size use Stripe to accept payments, grow revenue, and accelerate new business opportunities.",
        "website": "https://stripe.com",
        "investors": ["Sequoia Capital", "Andreessen Horowitz", "Khosla Ventures"],
        "key_metrics": ["25B+ ARR", "50M+ businesses", "135+ currencies", "46+ countries"],
        "why_match": "Enterprise-grade fintech platform looking for growth capital and strategic partnerships"
    },
    {
        "id": "real2",
        "name": "Canva",
        "company": "Canva",
        "headline": "Visual communication platform",
        "industry": "Enterprise SaaS",
        "sub_industry": "Design Tools",
        "location": "Sydney, Australia",
        "founded": 2013,
        "valuation": 26000000000,
        "arr": 2000000000,
        "employees": 4000,
        "stage": "Late Stage",
        "status": "Private",
        "description": "Canva is the world's leading visual communications platform with over 190 million monthly active users across 190+ countries.",
        "website": "https://canva.com",
        "investors": ["Sequoia Capital", "Blackbird Ventures", "General Catalyst"],
        "key_metrics": ["190M+ MAU", "$2B ARR", "190+ countries", "250B+ designs created"],
        "why_match": "Global design platform scaling with AI features"
    },
    {
        "id": "real3",
        "name": "Rippling",
        "company": "Rippling",
        "headline": "Workforce management platform",
        "industry": "Enterprise SaaS",
        "sub_industry": "HR Tech",
        "location": "San Francisco, CA",
        "founded": 2016,
        "valuation": 13500000000,
        "arr": 500000000,
        "employees": 3000,
        "stage": "Series E",
        "status": "Private",
        "description": "Rippling gives businesses one place to run HR, IT, and Finance. It brings together payroll, benefits, devices, apps, and more.",
        "website": "https://rippling.com",
        "investors": ["Founders Fund", "Coatue", "Greenoaks"],
        "key_metrics": ["$500M ARR", "50%+ YoY growth", "25K+ customers"],
        "why_match": "Fast-growing HR/IT platform looking for strategic investors"
    },
    {
        "id": "real4",
        "name": "Figma",
        "company": "Figma",
        "headline": "Collaborative design platform",
        "industry": "Enterprise SaaS",
        "sub_industry": "Design Tools",
        "location": "San Francisco, CA",
        "founded": 2012,
        "valuation": 12500000000,
        "arr": 700000000,
        "employees": 1500,
        "stage": "Late Stage",
        "status": "Private",
        "description": "Figma is a collaborative web application for interface design, with additional offline features enabled by desktop applications.",
        "website": "https://figma.com",
        "investors": ["Sequoia Capital", "Andreessen Horowitz", "Kleiner Perkins"],
        "key_metrics": ["$700M ARR", "4M+ users", "Enterprise adoption growing"],
        "why_match": "Design platform that transformed how teams build products"
    },
    {
        "id": "real5",
        "name": "SpaceX",
        "company": "SpaceX",
        "headline": "Space transportation and satellite communications",
        "industry": "Deep Tech",
        "sub_industry": "Space",
        "location": "Hawthorne, CA",
        "founded": 2002,
        "valuation": 350000000000,
        "arr": 15000000000,
        "employees": 13000,
        "stage": "Late Stage",
        "status": "Private",
        "description": "SpaceX designs, manufactures and launches rockets and spacecraft. Developed the first privately-funded liquid-fueled rocket to reach orbit (Falcon 1).",
        "website": "https://spacex.com",
        "investors": ["Founders Fund", "Fidelity", "Google"],
        "key_metrics": ["$15B ARR", "200+ launches", "Starlink: 3M+ subscribers"],
        "why_match": "Most ambitious space company in history"
    }
]
